AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: dailylife


Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'
    AllowedValues:
      - dev
      - stage
      - prod

Conditions:
  IsProd:
    !Equals [ !Ref Stage, "prod" ]
  IsDev:
    Fn::Equals:
      - 'dev'
      - !Ref Stage


Globals:
  Function:
    Runtime: java17
    MemorySize: 512
    Timeout: 15
    Environment:
      Variables:
        ASSOCIATION_TABLE: !Ref AssociationTable
        PARTY_TABLE: !Ref PartyTable
        COMMUNICATION_TABLE: !Ref CommunicationTable
        TASK_TABLE: !Ref TaskTable
        TASK_IN_PROGRESS_TABLE: !Ref TaskInProgressTable
        STAGE: !Ref Stage

Resources:


  AssociationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: "from_id"
          AttributeType: "S"
        - AttributeName: "to_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "from_id"
          KeyType: "HASH"
        - AttributeName: "to_id"
          KeyType: "RANGE"




  PartyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"

  CommunicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: "party_id"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "party_id"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"



  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"


  TaskInProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"



  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Daily Life AWS Api Gateway
      Description: Basic AWS Api Gateway
      OpenApiVersion: 3.0.1
      StageName: !Ref Stage
      DisableExecuteApiEndpoint: false

  PartyFindByIDLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: PartyFindByIDLambda
      Handler: com.burskey.dailylife.party.api.PartyGetByID::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PartyTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/{id}
            Method: get
            RequestParameters:
              - method.request.path.id:
                  Required: true
                  Caching: false

  PartySaveLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: PartySaveLambda
      Handler: com.burskey.dailylife.party.api.PartySave::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartyTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party
            Method: POST


  PartyCommunicationFindByIDLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: PartyCommunicationFindByIDLambda
      Handler: com.burskey.dailylife.party.api.CommunicationGetByID::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CommunicationTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/communication/{partyid}/{communication_id}
            Method: get

  CommunicationSaveLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: CommunicationSaveLambda
      Handler: com.burskey.dailylife.party.api.CommunicationSave::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommunicationTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/communication
            Method: POST


  PartyCommunicationFindByPartyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: PartyCommunicationFindByPartyLambda
      Handler: com.burskey.dailylife.party.api.CommunicationsGetByParty::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CommunicationTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/communications/{partyid}
            Method: get

  TaskSaveLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskSaveLambda
      Handler: com.burskey.dailylife.task.api.TaskHandler::handleRequest_save
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AssociationTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/task
            Method: POST


  TaskFindByIDLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskFindByIDLambda
      Handler: com.burskey.dailylife.task.api.TaskHandler::handleRequest_getTaskByID
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/task/{task_id}
            Method: get


  TaskFindByPartyIDLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskFindByPartyIDLambda
      Handler: com.burskey.dailylife.task.api.TaskHandler::handleRequest_getByParty
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskTable
        - DynamoDBReadPolicy:
            TableName: !Ref AssociationTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/tasks/{partyid}
            Method: get



  TaskStartLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskStartLambda
      Handler: com.burskey.dailylife.task.api.TaskHandler::handleRequest_Start
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskInProgressTable
        - DynamoDBReadPolicy:
            TableName: !Ref TaskTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/task/{task_id}/start
            Method: GET



  TaskInProgressGetByTaskLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskInProgressGetByTaskLambda
      Handler: com.burskey.dailylife.task.api.TaskInProgressHandler::handleRequest_GetByTask
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskInProgressTable
        - DynamoDBReadPolicy:
            TableName: !Ref AssociationTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/task/{task_id}/tasksinprogress
            Method: GET



  TaskInProgressChangeStatusLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda.zip
      FunctionName: TaskInProgressChangeStatusLambda
      Handler: com.burskey.dailylife.task.api.TaskInProgressHandler::handleRequest_changeStatus
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskInProgressTable
        - DynamoDBReadPolicy:
            TableName: !Ref TaskTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /party/taskinprogress/{tip_id}/changeTo/{status_id}
            Method: GET


Outputs:
  BasicAWSApiGateway:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${BasicAWSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
  BasicAWSApiGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref BasicAWSApiGateway
    Export:
      Name: BasicAWSApiGateway-RestApiId
  BasicAWSApiGatewayRootResourceId:
    Value: !GetAtt BasicAWSApiGateway.RootResourceId
    Export:
      Name: BasicAWSApiGateway-RootResourceId